### ISSUE TITLE
mat files broken?

### ISSUE THREAD

**Issue by grinsted** [bobkopp/LocalizeSL#1]
My matlab reports this error when i try the scripts in the scripts folder:

```
>> load('SLRProjections180124GRIDDEDcore_Tscens.mat')
Error using load
Unable to read MAT-file
C:\Users\ag\Documents\MATLAB\Assist\localizesl\IFILES\SLRProjections180124GRIDDEDcore_Tscens.mat.
Not a binary MAT-file. Try load -ASCII to read as text. 
```

**Comment by grinsted** [comment]
It seems they are not broken when i download them individually, but only when I download the zip file from the LocalizeSL github frontpage. Maybe it is my 7zip or it is github zip-packaging that breaks it. I will report back as i investigate.

**Comment by bobkopp** [comment]
I believe this is a trait of git-lfs -- you must either clone the repository on a system that has git-lfs installed, or download a zipped release that includes the MAT file.
