### ISSUE TITLE
Ocean useless for Baltic

### ISSUE THREAD

**Issue by grinsted** [bobkopp/LocalizeSL#2]
Some of the CMIP models have the Baltic as a lake instead of a sea. This results in crazy projections for places like Copenhagen.  

Perhaps there are also problems with the Mediterranean or near the English channel. 

Would it be possible to remove some models from specific regions from future studies?

**Comment by bobkopp** [comment]
This is already done to some extent -- extreme outlier models are excluded, as discussed in Kopp et al. 2014, but it is not possible to do this in an automatic fashion for everywhere in the world. The recommended approach if you disagree with the ocean dynamic projection in LocalizeSL would be to produce projections excluding the ocean dynamic component and add in projections from an alternative source. The generic scripts include an example of how to generate Monte Carlos that drop the background rate estimate; a similar approach could be taken here.

Note that LocalizeSL will be retired in favor of the Framework for Assessing Changes To Sea-level (https://github.com/radical-collaboration/facts) after the release of AR6.

**Comment by grinsted** [comment]
thanks
